### ISSUE TITLE
Warning: ENOENT, no such file or directory '*****-app\app\bower.json' 

### ISSUE THREAD

**Issue by ppaska** [start-angular/sb-admin-angular#24]
Dear,

I am trying to extend project with angular local storage module from bower:

I am running command:

> bower install angular-local-storage --save

bower.json updated

then I am trying to autoinject references by running command :
***-app>grunt wiredep
and getting Warning and obviously my index.html is not updated.

Running "wiredep:app" (wiredep) task
Warning: ENOENT, no such file or directory '*****-app\app\bower.json' Use --force to continue.
Aborted due to warnings.
grunt wiredep

The warning is because it tries to find a bower.json in ./app/ folder !

What is correct way of autoinjecting references with your project?

Thanks

**Comment by Amith92** [comment]
Hey @ppaska! We removed wiredep because we are lazyloading most of the bower components. If you want to autoinject the references then you will have to remove lazyloading and configure wiredep appropriately. Let me know if there is anything else. :)
