### ISSUE TITLE
Reload the sidebar

### ISSUE THREAD

**Issue by email2vimalraj** [start-angular/sb-admin-angular#32]
I've many different pages. I'm getting the dynamic data from each different pages. I would like to reload the sidebar menu with the data populated by a page. I'm unable to do it, it seems I've to manually reload the page again to get the data populated on the sidebar.

**Comment by sanketsahu** [comment]
That's something not related to this theme. It's Angular's basic. Use Data Services to have shared data and make sure your $digest cycle is running.

**Comment by email2vimalraj** [comment]
Thanks for a quick reply. Since I'm new to angular, my understanding is very limited. I'll google around and come back to you in case I need more help.

P.S: I use the data services.
