### ISSUE TITLE
How can I get data from MainContoller?

### ISSUE THREAD

**Issue by alexcc4** [start-angular/sb-admin-angular#33]
Hi, here is my code example: 

```
.state('dashboard', {
url:'/dashboard',
templateUrl: 'views/dashboard/main.html',
controller: 'MainController as mainController',}
)
.state('dashboard.code_demo', {
templateUrl: 'views/doc/codeDemo.html',
url: '/codeDemo',
controller: 'CodeController as codeController'}
)
```

When I want to get data(like mainController.somePro) from mainController(which main.html are the header part always loaded), It didn't work. Any suggestion? Thx.

**Comment by sanketsahu** [comment]
I am not sure about it and this question isn't related with SB Admin Angular theme. Please ask on StackOverflow. Closing this issue.

Thanks!
