### ISSUE TITLE
Windows User -  bower_components not found in zip file.

### ISSUE THREAD

**Issue by malathykrish** [start-angular/sb-admin-angular#39]
I am not able to find the folder browser_components, but looks like the index page has a lot of reference to it. I am using Windows and hence I just downloaded the zip file from github and tried to open the index page.

**Comment by sanketsahu** [comment]
Did you read the Readme for installation steps?

**Comment by malathykrish** [comment]
yup, I read the ReadMe, it did not have the installation steps for Windows.

**Comment by sanketsahu** [comment]
Everything remains the same. Step 2 may change a bit. You'll need to install node, npm, bower and grunt.

You can Google how to install them.

**Comment by sanketsahu** [comment]
And it's not browser_components. It's bower_components.

Please read about bower and related things.
