### ISSUE TITLE
bower ECONFLICT Unable to find suitable version for bootstrap

### ISSUE THREAD

**Issue by Roman-Blinkov** [start-angular/sb-admin-angular#4]
I got error from bower.
fix I am using: bower install --force-latest 
thank you

full bower output:`
bower angular#1.2.16            cached git://github.com/angular/bower-angular.git#1.2.16
bower angular#1.2.16          validate 1.2.16 against git://github.com/angular/bower-angular.git#1.2.16
bower json3#~3.3.1              cached git://github.com/bestiejs/json3.git#3.3.2
bower json3#~3.3.1            validate 3.3.2 against git://github.com/bestiejs/json3.git#~3.3.1
bower es5-shim#~3.1.0           cached git://github.com/es-shims/es5-shim.git#3.1.1
bower es5-shim#~3.1.0         validate 3.1.1 against git://github.com/es-shims/es5-shim.git#~3.1.0
bower bootstrap#~3.1.1          cached git://github.com/twbs/bootstrap.git#3.1.1
bower bootstrap#~3.1.1        validate 3.1.1 against git://github.com/twbs/bootstrap.git#~3.1.1
bower angular-resource#1.2.16   cached git://github.com/angular/bower-angular-resource.git#1.2.16
bower angular-resource#1.2.16 validate 1.2.16 against git://github.com/angular/bower-angular-resource.git#1.2.16
bower angular-cookies#1.2.16    cached git://github.com/angular/bower-angular-cookies.git#1.2.16
bower angular-cookies#1.2.16  validate 1.2.16 against git://github.com/angular/bower-angular-cookies.git#1.2.16
bower angular-sanitize#1.2.16   cached git://github.com/angular/bower-angular-sanitize.git#1.2.16
bower angular-sanitize#1.2.16 validate 1.2.16 against git://github.com/angular/bower-angular-sanitize.git#1.2.16
bower angular-animate#1.2.16    cached git://github.com/angular/bower-angular-animate.git#1.2.16
bower angular-animate#1.2.16  validate 1.2.16 against git://github.com/angular/bower-angular-animate.git#1.2.16
bower angular-touch#1.2.16      cached git://github.com/angular/bower-angular-touch.git#1.2.16
bower angular-touch#1.2.16    validate 1.2.16 against git://github.com/angular/bower-angular-touch.git#1.2.16
bower angular-route#1.2.16      cached git://github.com/angular/bower-angular-route.git#1.2.16
bower angular-route#1.2.16    validate 1.2.16 against git://github.com/angular/bower-angular-route.git#1.2.16
bower font-awesome#4.3.0        cached git://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower font-awesome#4.3.0      validate 4.3.0 against git://github.com/FortAwesome/Font-Awesome.git#4.3.0
bower angular-bootstrap#0.12.0  cached git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower angular-bootstrap#0.12.0         validate 0.12.0 against git://github.com/angular-ui/bootstrap-bower.git#0.12.0
bower oclazyload#~0.5.2                  cached git://github.com/ocombe/ocLazyLoad.git#0.5.2
bower oclazyload#~0.5.2                validate 0.5.2 against git://github.com/ocombe/ocLazyLoad.git#~0.5.2
bower angular-loading-bar#~0.7.0         cached git://github.com/chieffancypants/angular-loading-bar.git#0.7.1
bower angular-loading-bar#~0.7.0       validate 0.7.1 against git://github.com/chieffancypants/angular-loading-bar.git#~0.7.0
bower angular-ui-router#~0.2.13          cached git://github.com/angular-ui/ui-router.git#0.2.13
bower angular-ui-router#~0.2.13        validate 0.2.13 against git://github.com/angular-ui/ui-router.git#~0.2.13
bower angular-toggle-switch#~1.2.1       cached git://github.com/cgarvis/angular-toggle-switch.git#1.2.1
bower angular-toggle-switch#~1.2.1     validate 1.2.1 against git://github.com/cgarvis/angular-toggle-switch.git#~1.2.1
bower metisMenu#~1.1.3                   cached git://github.com/onokumus/metisMenu.git#1.1.3
bower metisMenu#~1.1.3                 validate 1.1.3 against git://github.com/onokumus/metisMenu.git#~1.1.3
bower angular-chart.js#~0.5.2            cached git://github.com/jtblin/angular-chart.js.git#0.5.2
bower angular-chart.js#~0.5.2          validate 0.5.2 against git://github.com/jtblin/angular-chart.js.git#~0.5.2
bower angular-mocks#1.2.16               cached git://github.com/angular/bower-angular-mocks.git#1.2.16
bower angular-mocks#1.2.16             validate 1.2.16 against git://github.com/angular/bower-angular-mocks.git#1.2.16
bower angular-scenario#1.2.16            cached git://github.com/angular/bower-angular-scenario.git#1.2.16
bower angular-scenario#1.2.16          validate 1.2.16 against git://github.com/angular/bower-angular-scenario.git#1.2.16
bower jquery#>= 1.9.0                    cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.9.0                  validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.9.0
bower bootstrap#~3.3.0                   cached git://github.com/twbs/bootstrap.git#3.3.2
bower bootstrap#~3.3.0                 validate 3.3.2 against git://github.com/twbs/bootstrap.git#~3.3.0
bower jquery#>= 1.9.1                    cached git://github.com/jquery/jquery.git#2.1.3
bower jquery#>= 1.9.1                  validate 2.1.3 against git://github.com/jquery/jquery.git#>= 1.9.1
bower Chart.js#~1.0.1                    cached git://github.com/nnnick/Chart.js.git#1.0.1
bower Chart.js#~1.0.1                  validate 1.0.1 against git://github.com/nnnick/Chart.js.git#~1.0.1
bower                                 ECONFLICT Unable to find suitable version for bootstrap
`

**Comment by Amith92** [comment]
Issue fixed. 'bower install' will do the trick now. Thanks for bringing it up.
