### ISSUE TITLE
insert directive

### ISSUE THREAD

**Issue by hymenoby** [start-angular/sb-admin-angular#45]
please i want to add angular-leafet directive but when i do all the app doesn't show .

angular.module("sbAdminApp", ["leaflet-directive"] )
    .controller('MapCtrl', [ '$scope', function($scope) {
        angular.extend($scope, {
            defaults: {
                scrollWheelZoom: false
            }
        });

```
}]);
```

apparently i can't add something like this "angular.module("sbAdminApp", ["leaflet-directive"] )"
after some tests i noticed that it is the leafet dependency that causes the error

**Comment by sanketsahu** [comment]
I am not sure what's happening and this doesn't look like it is an error related to this repo.

**Comment by hymenoby** [comment]
but where is the error coming from please? can you help me?

**Comment by sanketsahu** [comment]
Error comes in console debugger. Can you please check that?

**Comment by hymenoby** [comment]
when i put this line the template stops don't load anymore

**Comment by hymenoby** [comment]
so i can't see any error in the debugger

**Comment by sanketsahu** [comment]
Please put it on Stackoverflow and tag under AngularJS, the error must be something very simple like missing comma or semi-colon.

While adding to Stackoverflow, it would be good if you re-create this error in jsfiddle and add a link with the question. Someone will answer from the Angular community.

**Comment by hymenoby** [comment]
ok thanks
