### ISSUE TITLE
how to let it login first then goto index.html

### ISSUE THREAD

**Issue by tank2140896** [start-angular/sb-admin-angular#49]
i front-end use sb-admin-angular,and back-end use java.i want first login and handle login with java.if sucess then goto index.html;if i not login then whatever page i goto i want always first login.what i should to do by using sb-admin-angular?

**Comment by sanketsahu** [comment]
You can write APIs in Java and use Statellizer in the Angular app for login.

**Comment by sanketsahu** [comment]
Also, please raise bugs here. For help, you should post questions on StackOverflow

**Comment by tank2140896** [comment]
thank you.i first use this and dont't know the rules,sorry,not again!

**Comment by sanketsahu** [comment]
No problem! Thanks :-)
