### ISSUE TITLE
side menu with child items won't open

### ISSUE THREAD

**Issue by vgrafe** [start-angular/sb-admin-angular#5]
looks like the dropdown items are broken (tested right after cloning, installing dependencies and serving).

**Comment by Amith92** [comment]
What does your console say? Would help in knowing what exactly the issue is, because it is working fine with me as you can see in this [preview](http://start-angular.github.io/sb-admin-angular/preview/#/dashboard/home)

**Comment by vgrafe** [comment]
I have no errors and actually not a single log in the devtools when opening the page. Since the other javascript of the dashboard work, I'd guess metis menu silently crashes.

**Comment by vgrafe** [comment]
just cloned the project again, it works. sorry about that report.
